// Generated by CoffeeScript 1.3.3
(function() {
  var EventEmitter, Motors, compulsive, five, util, _, __,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require('events').EventEmitter;

  five = require('johnny-five');

  __ = require('johnny-five/lib/fn.js');

  _ = require('underscore');

  util = require('util');

  compulsive = require('compulsive');

  Motors = (function(_super) {

    __extends(Motors, _super);

    Motors.prototype.isMoving = false;

    Motors.prototype.isTurning = false;

    Motors.prototype.timer = false;

    function Motors(opts) {
      this.right = new five.Motor({
        pins: opts.right
      });
      this.left = new five.Motor({
        pins: opts.left
      });
      this.speed = !opts.speed ? 100 : opts.speed;
      this.motors = new five.Motors();
    }

    Motors.prototype.move = function(right, left) {
      this.status('moving');
      this.right.move(right);
      return this.left.move(left);
    };

    Motors.prototype.go = function(direction) {
      var speeds;
      switch (direction) {
        case 'forward':
          speeds = [this.speed, this.speed];
          break;
        case 'reverse':
          speeds = [-this.speed, -this.speed];
          break;
        case 'right':
          speeds = [0, this.speed];
          break;
        case 'left':
          speeds = [this.speed, 0];
      }
      return this.move(speeds);
    };

    Motors.prototype.accelerate = function(speed) {
      if (speed == null) {
        speed = 255;
      }
      return this.motors.accelerate(speed);
    };

    Motors.prototype.decelerate = function(speed) {
      if (speed == null) {
        speed = 0;
      }
      return this.motors.decelerate(speed);
    };

    Motors.prototype.turn = function(angle) {
      var direction;
      direction = angle < 180 ? 'left' : 'right';
      this.go(direction);
      return this.status('turning');
    };

    Motors.prototype.control = function(pos) {
      var diff, motors, speed;
      clearTimeout(this.timer);
      speed = Math.abs(pos.y * 255);
      diff = Math.abs(pos.x * speed);
      motors = pos.x < 0 ? {
        left: speed,
        right: speed - diff
      } : {
        left: speed - diff,
        right: speed
      };
      if (pos.y > 0) {
        motors.left *= -1;
        motors.right *= -1;
      }
      this.move(motors.right, motors.left);
      return this.timer = setTimeout(function() {
        return this.decelerate();
      }, 1000);
    };

    Motors.prototype.status = function(type) {
      this.isMoving = false;
      this.isTurning = false;
      this.emit(type, null);
      console.log(type);
      switch (type) {
        case 'moving':
          return this.isMoving = true;
        case 'turning':
          return this.isTurning = true;
      }
    };

    Motors.prototype.stop = function() {
      this.move(0, 0);
      return this.status('stopped');
    };

    return Motors;

  })(EventEmitter);

  module.exports = Motors;

}).call(this);
